name: Test and Coverage

on:
  push:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python3 -m venv venv        # Create a virtual environment
        source venv/bin/activate     # Activate the virtual environment
        pip install --upgrade pip    # Upgrade pip inside the venv
        pip install -r requirements.txt  # Install dependencies

    - name: Run Tests and Coverage
      run: |
        source venv/bin/activate     # Activate the virtual environment
        pytest --cov=.               # Run tests with coverage report

    - name: Upload coverage to Codecov
      run: |
        source venv/bin/activate     # Activate the virtual environment
        bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
